name: Docker Hub Pull

on:
  workflow_dispatch:
    inputs:
      oldImage:
        description: 'Image name to pull (user/image)'
        required: true
        default: 'user/mysql'
      tag:
        description: 'Version of the image to pull'
        required: true
        default: 'latest'
      newImage:
        description: 'Image name to save github/account/(image name)'
        required: true
        default: 'image'

env:
  # TODO: Change variable to your registry.
  REGISTRY: containers.pkg.github.com
  DOCKER: docker.io

# TODO: Add secrets DOCKER_USER, DOCKER_AUTH, and CR_PAT to your repo secrets
jobs:

  transfer:

    runs-on: ubuntu-latest

    steps:
      - uses: clarkbw/setup-docker@main
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_AUTH }}
          registry: $DOCKER

      - run: docker pull ${{ github.event.inputs.oldImage }}:${{ github.event.inputs.tag }}

      - uses: clarkbw/setup-docker@main
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
          registry: $REGISTRY

      - run: docker tag ${{ github.event.inputs.oldImage }}:${{ github.event.inputs.tag }} $REGISTRY/${{ github.event.inputs.newImage }}:${{ github.event.inputs.tag }}

      - run: docker push $REGISTRY/${{ github.event.inputs.newImage }}:${{ github.event.inputs.tag }}
